/* html.c
 * -----------------------------------------------------------------------
 * Copyright (C) 2025  Matteo Nicoli
 *
 * This file is part of TUR.
 *
 * TUR is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *	
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "commit.h"
#include "repo.h"
#include "settings.h"
#include "utils.h"

void generate_html_file(const repository_array_t *repos, settings_t settings)
{
	FILE *out = fopen(settings.output.val, "w");

	fprintf(out, "<!-- This file is automatically generated by TUR -->\n\n");

	for (size_t i = 0; i < repos->count; i++) {
		const repository_t repo = repos->repositories[i];
		const commit_refs_t *authored = repo.history->authored;
		const commit_refs_t *co_authored = repo.history->co_authored;

		fprintf(out, "<h2>%s</h2>\n\n", repo.name.val);
		
		if(repo.history->n_authored == 0) { goto co_authored; }

		fprintf(out, "\n<h3>Authored</h3>\n\n<ul>\n");
		
		for (size_t n_c = 0; n_c < repo.history->n_authored; n_c++) {
			fprintf(out, "\t<li><a href='%s' target='_blank>%s %s</a></li>",
					get_github_url(repo.url, authored->commits[n_c]->hash),
					authored->commits[n_c]->hash.val,
					time_to_string(authored->commits[n_c]->date).val);
		}

		fprintf(out, "</ul>\n");

	co_authored:
		
		if(repo.history->n_co_authored == 0) { continue; }

		fprintf(out, "\n<h3>Co-authored</h3>\n\n<ul>\n");
		
		for (size_t n_c = 0; n_c < repo.history->n_co_authored; n_c++) {
			fprintf(out, "\t\\item %s %s",
					co_authored->commits[n_c]->hash.val,
					time_to_string(co_authored->commits[n_c]->date).val);
		}

		fprintf(out, "</ul>\n");
	}

	fclose(out);
}
