/* html.c
 * -----------------------------------------------------------------------
 * Copyright (C) 2025  Matteo Nicoli
 *
 * This file is part of TUR.
 *
 * TUR is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *	
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "commit.h"
#include "repo.h"
#include "settings.h"
#include "utils.h"

#include <stdio.h>

static void generate_html_file_grouped(FILE *out, const
									   repository_t *repo,
									   const indexes_t *indexes)
{
	commit_t **const authored = indexes->authored;
	commit_t **const co_authored = indexes->co_authored;

	if(repo->history->n_authored == 0 && repo->history->n_co_authored == 0) { return; }

	fprintf(out, "<h2>%s</h2>\n\n", repo->name.val);
	
	if(repo->history->n_authored == 0) { goto co_authored; }

	fprintf(out, "\n<h3>Authored</h3>\n\n<ul>\n");
	
	for (size_t n_c = 0; n_c < repo->history->n_authored; n_c++) {
		fprintf(out, "\t<li><a href='%s' target='_blank'>%s</a> %s</li>",
				get_github_url(repo->url, authored[n_c]->hash).val,
				authored[n_c]->hash.val,
				time_to_string(authored[n_c]->date).val);
	}

	fprintf(out, "</ul>\n");

co_authored:
	
	if(repo->history->n_co_authored == 0) { return; }

	fprintf(out, "\n<h3>Co-authored</h3>\n\n<ul>\n");
	
	for (size_t n_c = 0; n_c < repo->history->n_co_authored; n_c++) {
		fprintf(out, "\t<li><a href='%s' target='_blank'>%s</a> %s</li>",
				get_github_url(repo->url, co_authored[n_c]->hash).val,
				co_authored[n_c]->hash.val,
				time_to_string(co_authored[n_c]->date).val);
	}

	fprintf(out, "</ul>\n");
}

static void generate_html_file_list(FILE *out, const
									repository_t *repo,
									const indexes_t *indexes)
{
	commit_t **const authored = indexes->authored;
	commit_t **const co_authored = indexes->co_authored;

	for (size_t n_c = 0; n_c < repo->history->n_authored; n_c++) {
		fprintf(out, "\t<li>[%s,A] <a href='%s' target='_blank'>%s</a> %s</li>",
				repo->name.val,
				get_github_url(repo->url, authored[n_c]->hash).val,
				authored[n_c]->hash.val,
				time_to_string(authored[n_c]->date).val);
	}

	for (size_t n_c = 0; n_c < repo->history->n_co_authored; n_c++) {
		fprintf(out, "\t<li>[%s,C] <a href='%s' target='_blank'>%s</a> %s</li>",
				repo->name.val,
				get_github_url(repo->url, co_authored[n_c]->hash).val,
				co_authored[n_c]->hash.val,
				time_to_string(co_authored[n_c]->date).val);
	}
}

void generate_html_file(const repository_array_t *repos, settings_t settings)
{
	FILE *out = fopen(settings.output.val, "w");

	fprintf(out, "<!-- This file is automatically generated by TUR -->\n\n");

	fprintf(out, "<h2>Commits:</h2>\n");

	if (!settings.grouped) {
		fprintf(out, "<ul>\n");
	}

	for (size_t i = 0; i < repos->count; i++) {
		const repository_t repo = repos->repositories[i];

		if (settings.grouped) {
			generate_html_file_grouped(out, &repo, &repo.history->indexes);
		} else {
			generate_html_file_list(out, &repo, &repo.history->indexes);
		}
	}

	if (!settings.grouped) {
		fprintf(out, "</ul>\n");
	}

	fclose(out);
}
