/* latex.c
 * -----------------------------------------------------------------------
 * Copyright (C) 2025  Matteo Nicoli
 *
 * This file is part of TUR.
 *
 * TUR is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *	
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "commit.h"
#include "repo.h"
#include "settings.h"

/*

% This file is automatically generated by TUR

\section{<name>}\n\label{sec:<name>}\n\n\subsection{Authored}\n\label{subsec:<name>-authored}\n\n\begin{itemize}

\end{itemize}

\subsection{Co-authored}
\label{subsec:<name>-co-authored}

*/

void generate_latex_file(const repository_array_t *repos, settings_t settings)
{
	FILE *out = fopen(settings.output.val, "w");
	commit_list_t *current = NULL;

	fprintf(out, "%% This file is automatically generated by TUR\n"
				 "%% This file is not standalone, you have to "
				 "include it in a LaTeX document with *hyperref*\n\n");

	for (size_t i = 0; i < repos->count; i++) {
		const repository_t repo = repos->repositories[i];

		fprintf(out, "\\section{%s}\n\\label{sec:%s}\n\n"
					 "\\subsection{Authored}\n\\label{subsec:%s-authored}\n\n"
					 "\\begin{itemize}",
					 repo.name.val, repo.name.val, repo.name.val);
		
		current = repo.history;
		do {
			fprintf(out, "\\item %s", current->commit.hash.val);
			current = current->parent;
		} while (current);
	}

	fclose(out);
}
