name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare environment for C compiling
      run: sudo apt-get install build-essential 
    - name: build tur and execute tests
      run: make
